//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Delivery
    {
        public string UserName { get; set; }
        public string OrderStatus { get; set; }
        public string OrderTracking { get; set; }
        public string OrderId { get; set; }
    }
}
